# TIKR Data Item Keys and Field Mappings
# This file contains the mapping between TIKR's internal data item IDs and their descriptions

keys = {
    4: "ebt excl. unusual items",
    5: "ebt excl. unusual items",
    7: "earnings from continuing operations",
    9: "basic eps",
    10: "gross profit",
    11: "total interest on borrowings",
    13: "interest expense",
    15: "net income_is",
    16: "net income to common incl extra items",
    17: "net interest income",
    21: "operating income",
    22: "operating income",
    24: "interest expense",
    25: "interest income",
    26: "non interest expense",
    27: "non interest income total",
    28: "revenue",
    29: "total revenues",
    31: "amortization of goodwill and intangible assets_is",
    32: "asset writedown",
    33: "asset writedown",
    34: "cost of goods sold",
    35: "property expenses",
    36: "policy acquisition /  underwriting costs",
    37: "cost of services provided",
    38: "currency exchange gains (loss)",
    39: "currency exchange gains (loss)",
    40: "earnings of discontinued operations",
    41: "depreciation & amortization_is",
    42: "extraordinary item & accounting change",
    43: "extraordinary item & accounting change",
    46: "(income) loss on equity invest.",
    47: "income (loss) on equity invest.",
    48: "income (loss) on equity invest.",
    49: "exploration / drilling costs",
    52: "finance div. revenues",
    55: "gain (loss) on sale of assets_is",
    56: "gain (loss) on sale of assets",
    57: "gain (loss) on sale of assets",
    60: "gain (loss) on sale of investments",
    61: "gain (loss) on sale of invest. & securities",
    62: "gain (loss) on sale of investments",
    63: "premiums and annuity revenues",
    64: "total interest and dividend income",
    65: "interest and investment income",
    66: "interest and investment income",
    67: "(income) loss on real estate property",
    68: "income (loss) on real estate property",
    70: "insurance division revenues",
    71: "impairment of oil gas & mineral properties",
    72: "in process r&d expenses",
    73: "insurance settlements",
    74: "insurance settlements",
    75: "income tax expense",
    76: "interest income on investments",
    77: "legal settlements",
    78: "legal settlements",
    79: "total mortgage banking activities",
    82: "interest expense",
    83: "minority interest_is",
    84: "non operating (income) expenses",
    85: "other non operating income (expenses)",
    86: "other non operating income (expenses)",
    87: "other unusual items",
    88: "other unusual items",
    89: "other operating expenses",
    90: "other revenues",
    91: "other revenues",
    92: "total other non interest expense",
    93: "total other non interest income",
    94: "policy benefits",
    95: "provision for bad debts",
    96: "pre-opening costs",
    97: "preferred dividend and other adjustments",
    99: "restructuring charges",
    100: "r&d expenses",
    101: "stock-based compensation (is)",
    102: "selling general & admin expenses",
    103: "selling general & admin expenses",
    104: "gain (loss) on sale of assets (rev)",
    105: "gain (loss) on sale of assets",
    106: "gain (loss) on sale of investment (rev)",
    107: "gain (loss) on sale of investments",
    108: "gain (loss) on sale of loans & receivables",
    109: "interest and dividend income",
    110: "interest and invest. income (rev)",
    111: "interest and investment income",
    112: "revenues",
    114: "allowance for borrowed funds used during construction",
    116: "allowance for equity funds used during construction",
    120: "asset management fee",
    125: "brokerage commission",
    126: "credit card fee",
    128: "commission and fees",
    135: "depreciation & amortization_is",
    139: "ebt incl. unusual items",
    142: "diluted eps excl extra items",
    152: "income (loss) on equity invest.",
    153: "salaries and other employee benefits",
    160: "federal deposit insurance",
    195: "(gain) loss on sale of loans",
    196: "gain (loss) on sale of loans",
    197: "amort. of goodwill & intang. assets",
    199: "underwriting & investment banking fee",
    205: "interest on deposits",
    209: "impairment of goodwill",
    212: "interest income on loans",
    215: "interest income on mortgage securities",
    237: "loan servicing revenue",
    241: "mortgage banking",
    244: "property management fee",
    247: "non-insurance activities expenses",
    248: "non-insurance activities revenues",
    250: "occupancy expense",
    255: "non operating income (expenses)",
    260: "other operating expenses",
    277: "provision for loan losses",
    278: "operations and maintenance",
    290: "trading and principal transactions",
    293: "tenant reimbursements",
    294: "reinsurance income or expense",
    298: "service charges on deposits",
    334: "rental revenues",
    336: "special dividends per share",
    337: "income from trading activities",
    338: "trust income",
    342: "weighted average diluted shares outstanding",
    356: "operating income",
    358: "other revenues",
    359: "provision for loan losses",
    360: "revenues before provison for loan losses",
    362: "credit card fee",
    363: "merger & restructuring charges",
    364: "total operating expenses",
    365: "total revenues",
    366: "compensation and benefits",
    367: "merger & restructuring charges",
    370: "net interest income",
    372: "other non operating income (expenses)",
    379: "net income to common excl. extra items",
    380: "total operating expenses",
    395: "amortization of goodwilland intangible assets_is",
    410: "revenues",
    411: "fuel & purchased power",
    1001: "total receivables",
    1002: "total cash and short term investments",
    1003: "net loans",
    1004: "net property plant and equipment",
    1005: "total preferred equity",
    1006: "total common equity",
    1007: "total assets",
    1008: "total current assets",
    1009: "total current liabilities",
    1010: "total deposits",
    1011: "total investments",
    1012: "total liabilities",
    1013: "total liabilities and equity",
    1015: "total real estate assets",
    1016: "accrued expenses",
    1017: "accrued expenses",
    1018: "accounts payable",
    1019: "accounts payable",
    1020: "accounts receivable",
    1021: "accounts receivable",
    1022: "comprehensive income and other",
    1024: "current portion of long-term debt",
    1025: "deferred charges long-term",
    1026: "deferred tax assets long-term",
    1027: "deferred tax liability non current",
    1028: "comprehensive income and other",
    1029: "finance division other current assets",
    1030: "finance division debt current",
    1031: "finance division other current liabilities",
    1032: "finance division loans and leases current",
    1033: "finance division loans and leases long-term",
    1034: "finance division other long-term assets",
    1035: "finance division debt non current",
    1036: "finance division other non current liabilities",
    1037: "insurance and annuity liabilities",
    1038: "long-term investments",
    1039: "investment in equity and preferred securities",
    1040: "other intangibles",
    1041: "other intangibles",
    1043: "inventory",
    1044: "investment securities",
    1045: "loans and lease receivables",
    1046: "short-term borrowings",
    1047: "short-term borrowings",
    1048: "notes receivable",
    1049: "long-term debt",
    1050: "loans receivable long-term",
    1051: "mortgage backed securities",
    1052: "minority interest_bs",
    1053: "minority interest_bs",
    1054: "long-term investments",
    1055: "other current assets",
    1056: "other current assets",
    1057: "other current liabilities",
    1058: "other current liabilities",
    1059: "other long-term assets",
    1060: "other long-term assets",
    1061: "other long-term liabilities",
    1062: "other long-term liabilities",
    1063: "preferred stock",
    1064: "preferred stock",
    1065: "prepaid expenses",
    1066: "prepaid expenses",
    1067: "proceeds from issuance of common stock",
    1068: "real estate assets held for sale",
    1069: "retained earnings",
    1070: "bank indebtedness",
    1071: "short-term investments",
    1072: "common shares outstanding",
    1074: "accumulated other income",
    1075: "accumulated other income",
    1076: "common stock net",
    1077: "common stock net",
    1078: "additional paid in capital",
    1079: "additional paid in capital",
    1080: "cash and cash equivalents",
    1081: "deposits with banks",
    1082: "common stock",
    1083: "common stock",
    1084: "goodwill",
    1085: "goodwill",
    1090: "trust preferred securities",
    1091: "pension and other employee benefits",
    1092: "cash and marketable securities",
    1093: "cash and marketable securities",
    1095: "deposits with banks",
    1096: "federal funds sold & resale agreements",
    1097: "allowance for loan losses",
    1098: "book value per share",
    1099: "tangible book value per share",
    1100: "total shareholders equity",
    2001: "net cash from operating activities",
    2002: "cash from financing activities",
    2003: "cash from investing activities",
    2004: "change in cash & cash equivalents",
    2005: "net income_cf",
    2006: "adjustments to net income",
    2007: "depreciation & amortization_cf",
    2008: "foreign exchange gains (losses)",
    2009: "gain (loss) on sale of assets_cf",
    2010: "gain (loss) on sale of investments_cf",
    2011: "deferred income taxes",
    2012: "equity in earnings of affiliates",
    2013: "minority interest_cf",
    2014: "impairment of goodwill_cf",
    2015: "sale of long-term investments",
    2016: "purchase of long-term investments",
    2017: "sale (purchase) of intangible assets",
    2018: "other investing activities",
    2019: "purchase of property, plant & equipment",
    2020: "sale of property, plant & equipment",
    2021: "investments in joint ventures",
    2022: "issuance of long-term debt",
    2023: "payment of long-term debt",
    2024: "proceeds (payments) of short-term borrowings",
    2025: "cash dividends paid",
    2026: "repurchase of common & preferred stock",
    2027: "sale of common & preferred stock",
    2028: "other financing activities",
    2029: "payment (proceeds) from bank indebtedness",
    2030: "free cash flow",
    2031: "asset writedown_cf",
    2032: "amortization of goodwill and intangible assets_cf",
    2033: "stock-based compensation (cf)",
    2034: "restructuring charges_cf",
    2035: "in process r&d expenses_cf",
    2036: "other unusual items_cf",
    2037: "provision for bad debts_cf",
    2038: "extraordinary item & accounting change_cf",
    2039: "other non cash items",
    2040: "changes in working capital",
    2041: "accounts receivable_cf",
    2042: "accounts payable_cf",
    2043: "other assets & liabilities",
    2044: "inventory_cf",
    2045: "deferred revenue",
    2046: "other working capital",
    2047: "acquisition_cf",
    2048: "cash from acquisitions",
    2049: "sale of business units",
    2050: "other operating activities",
    2051: "cash flow from continuing operations",
    2052: "cash flow from discontinued operations",
    2053: "capital expenditure",
    2054: "cash flow per share",
    2055: "free cash flow per share",
    2056: "cash and short term investments - beginning balance",
    2057: "cash and short term investments - ending balance",
    3001: "revenue",
    3002: "total revenue growth",
    3003: "revenue growth (1 yr)",
    3004: "revenue growth (3 yr cagr)",
    3005: "revenue growth (5 yr cagr)",
    3006: "revenue growth (10 yr cagr)",
    3007: "revenue growth (ltm vs py)",
    3008: "gross profit",
    3009: "gross profit growth",
    3010: "gross profit growth (1 yr)",
    3011: "gross profit growth (3 yr cagr)",
    3012: "gross profit growth (5 yr cagr)",
    3013: "gross profit growth (10 yr cagr)",
    3014: "gross profit growth (ltm vs py)",
    3015: "gross profit margin",
    3016: "operating income",
    3017: "operating income growth",
    3018: "operating income growth (1 yr)",
    3019: "operating income growth (3 yr cagr)",
    3020: "operating income growth (5 yr cagr)",
    3021: "operating income growth (10 yr cagr)",
    3022: "operating income growth (ltm vs py)",
    3023: "operating margin",
    3024: "ebitda",
    3025: "ebitda growth",
    3026: "ebitda growth (1 yr)",
    3027: "ebitda growth (3 yr cagr)",
    3028: "ebitda growth (5 yr cagr)",
    3029: "ebitda growth (10 yr cagr)",
    3030: "ebitda growth (ltm vs py)",
    3031: "ebitda margin",
    3032: "ebt",
    3033: "ebt growth",
    3034: "ebt growth (1 yr)",
    3035: "ebt growth (3 yr cagr)",
    3036: "ebt growth (5 yr cagr)",
    3037: "ebt growth (10 yr cagr)",
    3038: "ebt growth (ltm vs py)",
    3039: "ebt margin",
    3040: "net income",
    3041: "net income growth",
    3042: "net income growth (1 yr)",
    3043: "net income growth (3 yr cagr)",
    3044: "net income growth (5 yr cagr)",
    3045: "net income growth (10 yr cagr)",
    3046: "net income growth (ltm vs py)",
    3047: "net margin",
    3048: "eps",
    3049: "eps growth",
    3050: "eps growth (1 yr)",
    3051: "eps growth (3 yr cagr)",
    3052: "eps growth (5 yr cagr)",
    3053: "eps growth (10 yr cagr)",
    3054: "eps growth (ltm vs py)",
    3055: "book value per share",
    3056: "book value per share growth",
    3057: "book value per share growth (1 yr)",
    3058: "book value per share growth (3 yr cagr)",
    3059: "book value per share growth (5 yr cagr)",
    3060: "book value per share growth (10 yr cagr)",
    3061: "book value per share growth (ltm vs py)",
    3062: "free cash flow",
    3063: "free cash flow growth",
    3064: "free cash flow growth (1 yr)",
    3065: "free cash flow growth (3 yr cagr)",
    3066: "free cash flow growth (5 yr cagr)",
    3067: "free cash flow growth (10 yr cagr)",
    3068: "free cash flow growth (ltm vs py)",
    3069: "free cash flow per share",
    3070: "free cash flow per share growth",
    3071: "free cash flow per share growth (1 yr)",
    3072: "free cash flow per share growth (3 yr cagr)",
    3073: "free cash flow per share growth (5 yr cagr)",
    3074: "free cash flow per share growth (10 yr cagr)",
    3075: "free cash flow per share growth (ltm vs py)",
    3076: "shares outstanding",
    3077: "shares outstanding growth",
    3078: "shares outstanding growth (1 yr)",
    3079: "shares outstanding growth (3 yr cagr)",
    3080: "shares outstanding growth (5 yr cagr)",
    3081: "shares outstanding growth (10 yr cagr)",
    3082: "shares outstanding growth (ltm vs py)",
    3083: "roe",
    3084: "roa",
    3085: "roic",
    3086: "debt / equity",
    3087: "debt / ebitda",
    3088: "interest coverage",
    3089: "current ratio",
    3090: "quick ratio",
    3091: "asset turnover",
    3092: "inventory turnover",
    3093: "receivables turnover",
    3094: "payables turnover",
    3095: "cash conversion cycle",
    3096: "gross profit per share",
    3097: "operating income per share",
    3098: "ebitda per share",
    3099: "ebt per share",
    3100: "revenue per share",
    3101: "tangible book value per share",
    3102: "cash flow from operations per share",
    3103: "capex per share",
    3104: "net cash per share",
    3105: "working capital per share",
    3106: "enterprise value",
    3107: "price / book",
    3108: "price / sales",
    3109: "price / cash flow",
    3110: "enterprise value / sales",
    3111: "enterprise value / ebitda",
    3112: "enterprise value / ebit",
    3113: "price / tangible book",
    3114: "dividend yield",
    3115: "dividend per share",
    3116: "dividend growth (1 yr)",
    3117: "dividend growth (3 yr cagr)",
    3118: "dividend growth (5 yr cagr)",
    3119: "dividend growth (10 yr cagr)",
    3120: "payout ratio",
    3121: "free cash flow yield",
    3122: "earnings yield",
    3123: "free cash flow / net income",
    3124: "working capital",
    3125: "net cash",
    3126: "total debt",
    3127: "net debt",
    3128: "market capitalization",
    3129: "shares outstanding (basic)",
    3130: "shares outstanding (diluted)",
    3131: "float",
    3132: "insider ownership",
    3133: "institutional ownership",
    3134: "short interest",
    3135: "short ratio",
    3136: "beta",
    3137: "52 week high",
    3138: "52 week low",
    3139: "rsi",
    3140: "price / earnings",
    3141: "trailing 12 month pe",
    3142: "forward pe",
    3217: "weighted average basic shares outstanding",
    4053: "ltm pe ratio",
    4419: "ltm pe ratio",
    4074: "gross margins %",
    4094: "net income to common incl extra items margins %",
    4181: "net income to common excl. extra items margins %",
    4376: "effective tax rate %",
    4051: "ebitda",
    3168: "r&d expenses",
    21561: "selling and marketing expense",
    21562: "general and administrative expense",
    21674: "ebitdar",
    2171: "depreciation & amortization",
    2182: "amortization of goodwill and intangible assets",
    2160: "total depreciation & amortization",
    2026: "(gain) loss from sale of asset",
    2090: "(gain) loss on sale of investments",
    2127: "stock-based compensation",
    2135: "tax benefit from stock options",
    2081: "net cash from discontinued operations",
    2047: "other operating activities",
    2018: "change in accounts receivable",
    2140: "change in inventories",
    2017: "change in accounts payable",
    2139: "change in unearned revenues",
    2101: "change in income taxes",
    2045: "change in other net operating assets",
    2006: "cash from operations",
    2010: "change in net working capital",
    2042: "sale of property, plant, and equipment",
    2057: "cash acquisitions",
    2077: "divestitures",
    2029: "sale (purchase) of intangible assets",
    2027: "investment in marketable and equity securities",
    2051: "other investing activities",
    2005: "cash from investing",
    2161: "total debt issued",
    2166: "total debt repaid",
    2169: "issuance of common stock",
    2164: "repurchase of common stock",
    2050: "other financing activities",
    2004: "cash from financing",
    2144: "foreign exchange rate adjustments",
    2093: "net change in cash",
    2055: "cash and cash equivalents, beginning of period",
    2056: "cash and cash equivalents, end of period",
    3028: "cash interest paid",
    3053: "cash taxes paid",
    43923: "cash flow per share",
    1096: "cash and equivalents",
    1069: "short term investments",
    1206: "other receivables",
    1212: "prepaid expenses",
    1117: "deferred tax assets current",
    1104: "restricted cash",
    1169: "gross property plant and equipment",
    1075: "accumulated depreciation",
    1171: "goodwill",
    1297: "current portion of long-term debt",
    1090: "current portion of capital lease obligations",
    1094: "current income taxes payable",
    1074: "unearned revenue current",
    1183: "capital leases",
    1256: "unearned revenue non current",
    1276: "total liabilities",
    1214: "preferred stock convertible",
    1065: "preferred stock - others",
    1103: "common stock",
    1084: "additional paid in capital",
    1222: "retained earnings",
    1275: "total equity",
    24153: "total shares out. on filing date",
    4020: "book value/share",
    1310: "tangible book value",
    4156: "tangible book value/share",
    4173: "total debt",
    4364: "net debt",
    3063: "equity method investments",
    3098: "land",
    3023: "buildings",
    24216: "construction in progress",
    3085: "full time employees"
}

# Statement configurations for API calls
statements = [
    {
        'statement': 'income_statement',
        'keys': {
            'Revenues': 28,
            'Total Revenues': 112,
            'Total Revenues YoY': '',
            'Cost of Goods Sold': 34,
            'Gross Profit': 10,
            'Gross Profit YoY': '',
            '% Gross Margins': 4074,
            'Selling General & Admin Expenses': 102,
            'R&D Expenses': 3168,
            'Total Operating Expenses': 380,
            'Operating Income': 21,
            'Operating Income YoY': '',
            '% Operating Margins': 4053,
            'Interest Expense': 82,
            'Interest And Investment Income': 65,
            'Currency Exchange Gains (Loss)': 38,
            'Other Non Operating Income (Expenses)': 85,
            'EBT Excl. Unusual Items': 4,
            'Gain (Loss) On Sale Of Investments': 62,
            'Gain (Loss) On Sale Of Assets': 104,
            'Asset Writedown': 2019,
            'In Process R&D Expenses': 72,
            'Legal Settlements': 77,
            'Other Unusual Items': 87,
            'EBT Incl. Unusual Items': 139,
            'Income Tax Expense': 75,
            'Earnings From Continuing Operations': 7,
            'Earnings Of Discontinued Operations': 40,
            'Net Income to Company': 41571,
            'Net Income': 15,
            'Net Income to Common Incl Extra Items': 16,
            '% Net Income to Common Incl Extra Items Margins': 4094,
            'Net Income to Common Excl. Extra Items': 379,
            '% Net Income to Common Excl. Extra Items Margins': 4181,
            'Diluted EPS Excl Extra Items': 142,
            'Diluted EPS Excl Extra Items YoY': '',
            'Weighted Average Diluted Shares Outstanding': 342,
            'Weighted Average Diluted Shares Outstanding YoY': '',
            'Weighted Average Basic Shares Outstanding': 3217,
            'Weighted Average Basic Shares Outstanding YoY': '',
            'Basic EPS': 9,
            'EBITDA': 4051,
            'EBITDA YoY': '',
            'EBITDAR': 21674,
            'R&D Expense': 3168,
            'Selling and Marketing Expense': 21561,
            'General and Administrative Expense': 21562,
            'Effective Tax Rate %': 4376
        }
    },
    {
        'statement': 'cashflow_statement',
        'keys': {
            'Net Income': 15,
            'Depreciation & Amortization': 2171,
            'Amortization of Goodwill and Intangible Assets': 2182,
            'Total Depreciation & Amortization': 2160,
            '(Gain) Loss From Sale Of Asset': 2026,
            '(Gain) Loss on Sale of Investments': 2090,
            'Asset Writedown & Restructuring Costs': 2019,
            'Stock-Based Compensation': 2127,
            'Tax Benefit from Stock Options': 2135,
            'Net Cash From Discontinued Operations': 2081,
            'Other Operating Activities': 2047,
            'Change In Accounts Receivable': 2018,
            'Change In Inventories': 2140,
            'Change In Accounts Payable': 2017,
            'Change in Unearned Revenues': 2139,
            'Change In Income Taxes': 2101,
            'Change in Other Net Operating Assets': 2045,
            'Cash from Operations': 2006,
            'Change in Net Working Capital': 2010,
            'Capital Expenditure': 2021,
            'Sale of Property, Plant, and Equipment': 2042,
            'Cash Acquisitions': 2057,
            'Divestitures': 2077,
            'Sale (Purchase) of Intangible assets': 2029,
            'Investment in Marketable and Equity Securities': 2027,
            'Other Investing Activities': 2051,
            'Cash from Investing': 2005,
            'Total Debt Issued': 2161,
            'Total Debt Repaid': 2166,
            'Issuance of Common Stock': 2169,
            'Repurchase of Common Stock': 2164,
            'Other Financing Activities': 2050,
            'Cash from Financing': 2004,
            'Foreign Exchange Rate Adjustments': 2144,
            'Net Change in Cash': 2093,
            'Free Cash Flow': '',
            'Free Cash Flow YoY': '',
            '% Free Cash Flow Margins': '',
            'Cash and Cash Equivalents, Beginning of Period': 2055,
            'Cash and Cash Equivalents, End of Period': 2056,
            'Cash Interest Paid': 3028,
            'Cash Taxes Paid': 3053,
            'Cash Flow per Share': 43923
        }
    },
    {
        'statement': 'balancesheet_statement',
        'keys': {
            'Cash And Equivalents': 1096,
            'Short Term Investments ': 1069,
            'Total Cash And Short Term Investments ': 1002,
            'Accounts Receivable': 1021,
            'Other Receivables ': 1206,
            'Notes Receivable': 1048,
            'Total Receivables': 1001,
            'Inventory ': 1043,
            'Prepaid Expenses': 1212,
            'Deferred Tax Assets Current': 1117,
            'Restricted Cash': 1104,
            'Other Current Assets ': 1055,
            'Total Current Assets ': 1008,
            'Gross Property Plant And Equipment': 1169,
            'Accumulated Depreciation': 1075,
            'Net Property Plant And Equipment ': 1004,
            'Long-term Investments ': 1054,
            'Goodwill': 1171,
            'Other Intangibles': 1040,
            'Loans Receivable Long-Term ': 1050,
            'Deferred Tax Assets Long-Term ': 1026,
            'Other Long-Term Assets ': 1060,
            'Total Assets ': 1007,
            'Accounts Payable': 1018,
            'Accrued Expenses': 1016,
            'Short-term Borrowings ': 1046,
            'Current Portion of Long-Term Debt': 1297,
            'Current Portion of Capital Lease Obligations': 1090,
            'Current Income Taxes Payable ': 1094,
            'Unearned Revenue Current ': 1074,
            'Other Current Liabilities ': 1057,
            'Total Current Liabilities ': 1009,
            'Long-Term Debt ': 1049,
            'Capital Leases': 1183,
            'Unearned Revenue Non Current': 1256,
            'Deferred Tax Liability Non Current ': 1027,
            'Other Non Current Liabilities ': 1062,
            'Total Liabilities ': 1276,
            'Preferred Stock Convertible ': 1214,
            'Preferred Stock - Others ': 1065,
            'Total Preferred Equity ': 1005,
            'Common Stock': 1103,
            'Additional Paid In Capital': 1084,
            'Retained Earnings': 1222,
            'Comprehensive Income and Other ': 1028,
            'Total Common Equity ': 1006,
            'Total Equity ': 1275,
            'Total Liabilities And Equity ': 1013,
            'Total Shares Out. on Filing Date ': 24153,
            'Book Value/Share ': 4020,
            'Tangible Book Value': 1310,
            'Tangible Book Value/Share ': 4156,
            'Total Debt ': 4173,
            'Net Debt': 4364,
            'Equity Method Investments ': 3063,
            'Land ': 3098,
            'Buildings ': 3023,
            'Construction In Progress ': 24216,
            'Full Time Employees': 3085
        }
    },
] 