# TIKR Scraper Secrets Configuration
# For Streamlit Community Cloud deployment

# Credentials
TIKR_EMAIL = "your_email@example.com"
TIKR_PASSWORD = "your_password"

# Deployment flag - Set to "true" when deploying to Streamlit Cloud
IS_DEPLOYMENT = "true"

# Pre-generated access token (required for deployment)
# Generate this locally and paste it here for deployment
TOKEN = "your_locally_generated_token" 